CREATE TABLE USER(
    ID BIGINT PRIMARY KEY  NOT NULL AUTO_INCREMENT ,
    USER_NAME NVARCHAR(40) NOT NULL ,
    ENCRYPTED_PASSWORD VARCHAR(130) NOT NULL ,
    STATUS BIT NOT NULL
);


CREATE TABLE ROLE
(
    ID   INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) UNIQUE NOT NULL
);



CREATE TABLE USER_ROLE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT  NOT NULL,
    ROLE_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

ALTER TABLE USER ADD CONSTRAINT
USER_UK UNIQUE (USER_NAME);

alter table ROLE change NAME ROLE_NAME varchar(50) not null;
