INSERT INTO USER(USER_NAME,ENCRYPTED_PASSWORD,STATUS) VALUES
('user','$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu',1);

INSERT INTO USER(USER_NAME,ENCRYPTED_PASSWORD,STATUS) VALUES
('admin','$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu',1);


insert into ROLE (ROLE_NAME)
values ('ROLE_ADMIN');


insert into ROLE (ROLE_NAME)
values ('ROLE_USER');


INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES(1,2);


INSERT INTO USER_ROLE(USER_ID,ROLE_ID)
VALUES (2,1);



